# -*- coding: utf-8 -*-
"""cursobasicopython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11v4hLRiaI_OH6gjDpjFoMNvdYSOIm7rm
"""



# Lógica de Programação

#  Passo 0 - Entender o desafio que você quer resolver

# Passo 1 - Percorrer todos os arquivos da pasta base de dados(pasta vendas)
import os
#-biblioteca para as instruções os.
import pandas as pd
# as pd: pd é a forma de abreviar o nome pandas.
#use pd ao invés de escrever pandas
#pandas é usado para trabalhar com bases de dados.


lista_arquivo = os.listdir("/content/drive/MyDrive/cursopython/vendas")
#- os.listdir() serve para ler todos os arquivos em uma pasta.
#-informar o endereço da pasta em aspas string.
#display(lista_arquivo)

tabela_total = pd.DataFrame()
#pd.DataFrame serve para criar tabelas no Python
# Passo 2 - Importar as bases de dados de vendas
for arquivo in lista_arquivo:
  #se tem "vendas" no nome do arquivo, então
  if "Vendas" in arquivo:
    #importar arquivo
    #lower tranforma todo o texto em letra minúscula
    tabela = pd.read_csv(f"/content/drive/MyDrive/cursopython/vendas/{arquivo}")
        #pd.read_ serve para ler arquivos.
    #após o _ informe o formato do arquivo.
    tabela_total = tabela_total.append(tabela)
    #.append está adicionando o valor da variavel tabela na variavel tabela_total
    #.append adiciona dados na planilha


# Passo 3 - Tratar/compilar as bases de dados
display(tabela_total)

# Passo 4 - Calcular o produto mais vendido (em quantidade)
tabela_produtos = tabela_total.groupby("Produto").sum()
#.groupby serve para agrupar colunas
#.sum está somando as outras colunas
tabela_produtos = tabela_produtos[["Quantidade Vendida"]]
#Filtrar as colunas que desejo.
# colocar dois [[]] para duas ou mais colunas.
display(tabela_produtos)

# Passo 5 - Calcular o produto que mais faturou (em faturamento)

# Passo 6 - Calcular a loja/cidade que mais vendeu (em faturamento) - criar um gráfico/dashboard

from google.colab import drive
drive.mount('/content/drive')